name: iOS CI
on: [push, pull_request]
jobs:
  build-test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with: { xcode-version: '16.2' }
      - run: brew install swiftformat swiftlint
      - run: swiftformat --lint .
      - run: swiftlint
      - run: xcodebuild -scheme "AI Journal App" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' clean build test | xcpretty || true
